### ISSUE TITLE
[Bug]: 打不开软件

### ISSUE THREAD

**Issue by MerlinAmbr0sius** [ZGGSONG/STranslate#260]
### 预期情况

打不开软件。

### 实际情况

打不开软件，管理员运行也打不开，连续点击多次出现“多开检测，程序已在运行”框体，但是右下角托盘里并没有图标，进程里也搜不到，快捷键也无效，呼不出来。

### 复现方法

之前用的老版本可以打开，但是忘记是哪个版本了，今天更新了新版本打不开了。
卸载重新下载后解压缩包，依旧打不开。

### 日志信息

2024-11-20 14:51:36.070 [INF] STranslate_1.2.10.1117 Closed...

2024-11-20 14:51:36.401 [INF] STranslate_1.2.10.1117 Closed...

2024-11-20 14:52:02.432 [INF] STranslate_1.2.10.1117 Closed...

2024-11-20 14:53:52.309 [INF] STranslate_1.2.10.1117 Closed...

### 我确认已更新至最新版本

- [X] 是

### 我确认已查询历史issues

- [X] 是

**Comment by MerlinAmbr0sius** [comment]
[stranslate.json](https://github.com/user-attachments/files/17828997/stranslate.json)
老版本实在想不起来了。

**Comment by MerlinAmbr0sius** [comment]
试了，还是不行，但是另一台电脑可以打开，估计是这台电脑的window11哪里出了问题吧。不折腾了，等下次重装系统了再用回来。

**Comment by sudo-YY** [comment]
试了一下 用你的配置 win11也没有闪退

**Comment by MerlinAmbr0sius** [comment]
另一台能打开的也是win11……

**Comment by MerlinAmbr0sius** [comment]
错误应用程序名称: STranslate.exe，版本: 1.2.11.1121，时间戳: 0x67110000
错误模块名称: KERNELBASE.dll，版本: 10.0.22621.4391，时间戳: 0x7433a115

**Comment by zhiyu1998** [comment]
我也是打不开，已经稳定运行了一年了，前几天升级了版本就🐔了，然后我是这样
1. `C:\Users\Administrator\AppData\Local\STranslate` 搬运这个文件夹到其他文件夹下，暂时存储下
2. 下一个最新版本`https://stranslate.zggsong.com/download.html`，版本是`1.2.11.1121`，然后以管理员身份打开就可以了

**Comment by ZGGSONG** [comment]
可以吧旧配置中的敏感数据移除后并且能触发无法打开软件的配置发我一份嘛，我调试一下看啥问题

**Comment by sudo-YY** [comment]
好的

> 可以吧旧配置中的敏感数据移除后并且能触发无法打开软件的配置发我一份嘛，我调试一下看啥问题
> 
> 邮箱: [zggsong@foxmail.com](mailto:zggsong@foxmail.com)

**Comment by sudo-YY** [comment]
> 可以吧旧配置中的敏感数据移除后并且能触发无法打开软件的配置发我一份嘛，我调试一下看啥问题
> 
> 邮箱: [zggsong@foxmail.com](mailto:zggsong@foxmail.com)

好的

**Comment by pheotry** [comment]
> 可以吧旧配置中的敏感数据移除后并且能触发无法打开软件的配置发我一份嘛，我调试一下看啥问题
> 
> 邮箱: [zggsong@foxmail.com](mailto:zggsong@foxmail.com)

我也打不开，我是通过scoop install scoop-cn/stranslate安装的，也手动在安装位置创建了portable_config文件夹，还是没用。

这个是事件管理器的报错信息：
```txt
Application: STranslate.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at STranslate.Util.ShortcutUtil.GetDirectoryFileList(String target)
   at STranslate.Util.ShortcutUtil.ShortCutDelete(String path, String target)
   at STranslate.Util.ShortcutUtil.UnSetStartup()
   at STranslate.Helper.ConfigHelper.StartupOperate(Boolean isStartup)
   at STranslate.Helper.ConfigHelper.InitialOperate()
   at STranslate.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at STranslate.App.Main()

```

**Comment by ZGGSONG** [comment]
> 我也打不开，我是通过scoop install scoop-cn/stranslate安装的，也手动在安装位置创建了portable_config文件夹，还是没用。
> 
> 这个是事件管理器的报错信息：

非常感谢你提供的信息，我大概能判断问题出在哪里了。我尝试修复该问题并临时打包了一个版本，你可以试试看能不能正常打开[stranslate_try_fix_can.t_open_aa196de867e7cf315d563c39b51e6b88c14d5c1f.zip](https://github.com/ZGGSONG/STranslate/releases/download/0.01/stranslate_try_fix_can.t_open_aa196de867e7cf315d563c39b51e6b88c14d5c1f.zip)

**Comment by pheotry** [comment]
> > 我也打不开，我是通过scoop install scoop-cn/stranslate安装的，也手动在安装位置创建了portable_config文件夹，还是没用。
> > 这个是事件管理器的报错信息：
> 
> 非常感谢你提供的信息，我大概能判断问题出在哪里了。我尝试修复该问题并临时打包了一个版本，你可以试试看能不能正常打开[stranslate_try_fix_can.t_open_aa196de867e7cf315d563c39b51e6b88c14d5c1f.zip](https://github.com/ZGGSONG/STranslate/releases/download/0.01/stranslate_try_fix_can.t_open_aa196de867e7cf315d563c39b51e6b88c14d5c1f.zip)

不行

```txt
Application: STranslate.exe
CoreCLR Version: 8.0.1124.51707
.NET Version: 8.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: The value cannot be an empty string. (Parameter 'path')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.IO.Directory.CreateDirectory(String path)
   at STranslate.Util.ShortcutUtil.GetDirectoryFileList(String target)
   at STranslate.Util.ShortcutUtil.ShortCutDelete(String path, String target)
   at STranslate.Util.ShortcutUtil.UnSetStartup()
   at STranslate.Helper.ConfigHelper.StartupOperate(Boolean isStartup)
   at STranslate.Helper.ConfigHelper.InitialOperate()
   at STranslate.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at STranslate.App.Main()

```

**Comment by ZGGSONG** [comment]
https://github.com/ZGGSONG/STranslate/releases/download/0.01/stranslate_try_fix_cann.t_open_v2_aa196de867e7cf315d563c39b51e6b88c14d5c1f.zip

**Comment by ZGGSONG** [comment]
我怀疑是你的注册表路径下`计算机\HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders`没有`Startup`字段

**Comment by pheotry** [comment]
> https://github.com/ZGGSONG/STranslate/releases/download/0.01/stranslate_try_fix_cann.t_open_v2_aa196de867e7cf315d563c39b51e6b88c14d5c1f.zip

可以启动了，Startup也是有的，这个微信OCR是只支持旧版微信是吧，新版4.0不行吧

**Comment by MerlinAmbr0sius** [comment]
最新的版本，可以正常打开了。

**Comment by ZGGSONG** [comment]
> 这个微信OCR是只支持旧版微信是吧，新版4.0不行吧

4.0不是还在内测嘛，出正式版我再去适配

**Comment by ZGGSONG** [comment]
> 最新的版本，可以正常打开了。

请问是上面的临时版本，还是最新的release版本
