### ISSUE TITLE
[Bug]: openaiocr在图片设置为高质量时报错

### ISSUE THREAD

**Issue by forever-lwy** [ZGGSONG/STranslate#287]
### 预期情况

正常识别图片

### 实际情况

把图片质量设置为高质量时识别会失败，我是使用new-api中转的，看信息猜测是new-api不能处理图片格式？直接使用官方api时不知道会不会有问题。

### 复现方法

把图片质量设为高后直接使用openaiocr

### 日志信息

2024-12-24 15:15:06.123 [ERR] OCR失败: Internal Server Error {"error":{"message":"decode base64 image data failed: fail to decode image config(webp): riff: missing RIFF chunk header (request id: 202412241515063488130838TCRuhsV)","type":"new_api_error","param":"","code":"convert_request_failed"}}
System.Exception: Internal Server Error
 ---> System.Exception: {"error":{"message":"decode base64 image data failed: fail to decode image config(webp): riff: missing RIFF chunk header (request id: 202412241515063488130838TCRuhsV)","type":"new_api_error","param":"","code":"convert_request_failed"}}
   --- End of inner exception stack trace ---
   at STranslate.Util.HttpUtil.ResponseCheckAsync(HttpResponseMessage response, CancellationToken token)
   at STranslate.Util.HttpUtil.GetResponseContentAsync(HttpResponseMessage response, CancellationToken token)
   at STranslate.Util.HttpUtil.PostAsync(String url, String req, Dictionary`2 queryParams, Dictionary`2 headers, CancellationToken token, Int32 timeout)
   at STranslate.ViewModels.Preference.OCR.OpenAIOCR.ExecuteAsync(Byte[] bytes, LangEnum lang, CancellationToken cancelToken)
   at STranslate.ViewModels.Preference.OCRScvViewModel.ExecuteAsync(Byte[] bytes, WindowType showErrorToast, Nullable`1 token, LangEnum lang)
   at STranslate.ViewModels.OCRViewModel.OCRHandler(Byte[] bytes, Nullable`1 token)

### 额外信息

不确定这算bug还是功能请求，因为报错似乎不是软件的问题，如果是new-api的问题还是希望大佬能适配一下，谢谢。

### 我确认已更新至最新版本

- [X] 是

### 我确认已查询历史issues

- [X] 是

**Comment by ZGGSONG** [comment]
> 把图片质量设置为高质量时识别会失败

如果设置成中或者低呢

**Comment by forever-lwy** [comment]
中和低是正常的，只有高不可以。

**Comment by ZGGSONG** [comment]
> 中和低是正常的，只有高不可以。

那就应该是中转有文件大小限制，高用的时bmp解码器，测试的时候发现即便一块不大的区域也可能几十上百MB大小，所以在线服务还是使用中等或者低就行了，对结果基本没啥影响

```cs
private ImageFormat GetImageFormat()
{
    return (_configHelper.CurrentConfig?.OcrImageQuality ?? OcrImageQualityEnum.Medium) switch
    {
        OcrImageQualityEnum.Medium => ImageFormat.Png,
        OcrImageQualityEnum.Low => ImageFormat.Jpeg,
        _ => ImageFormat.Bmp
    };
}
```

**Comment by forever-lwy** [comment]
好的，我还以为中和低是压缩画质了，高是原画质呢
